language: r

matrix:
  include:
    - dist: xenial
      r: release
    - dist: xenial
      r: devel
    - os: osx
      r: release

sudo: false

cache: packages
warnings_are_errors: true
r_check_args: "--as-cran"

# 3/8/2019 time checks are failing on R-devel
env: _R_CHECK_SYSTEM_CLOCK_ = 0
