testthat::context("test-rational-functions")

testthat::test_that("Test S4 functions", {
  a <- rational(5L, 2L, "S4")
  expect_equal(2, floor(a))
  expect_equal(-1, sign(rational(-1L, 2L, "S4")))
  expect_equal(2, round(rational(5L, 2L, "S4"), 0))
  x <- abs(rational(-2L, 3L, "S4"))
  expect_true("rationalS4" %in% class(x))
  expect_true(2/3 == abs(x))
  b <- rational(2L, 5L, "S4")
  expect_equal(log(2/5), log(b))
  expect_equal(log10(2/5), log10(b))
  expect_equal(logb(2/5, base = 5), logb(b, base = 5))
  expect_equal(log2(2/5), log2(b))
  expect_equal(gamma(2/5), gamma(b))
  expect_true(3 == max(rational(c(2L, 3L), c(5L, 1L), "S4")))
  expect_true(2/5 == min(rational(c(2L, 3L), c(5L, 1L), "S4")))
  expect_true(is.list(range(rational(c(2L, 3L), c(5L, 1L), "S4"))))
  expect_true(range(rational(c(2L, 3L), c(5L, 1L), "S4"))[[1]] == rational(2L, 5L, "S4"))
  expect_true(6/5 == prod(rational(c(2L, 3L), c(5L, 1L), "S4")))
  expect_true(17/5 == sum(rational(c(2L, 3L), c(5L, 1L), "S4")))
})

testthat::test_that("Test S3 functions", {
  a <- rational(5L, 2L, "S3")
  expect_equal(2, floor(a))
  expect_equal(-1, sign(rational(-1L, 2L, "S3")))
  expect_equal(2, round(rational(5L, 2L, "S3"), 0))
  x <- abs(rational(-2L, 3L, "S3"))
  expect_true("rationalS3" %in% class(x))
  expect_true(2/3 == abs(x))
  b <- rational(2L, 5L, "S3")
  expect_equal(log(2/5), log(b))
  expect_equal(log10(2/5), log10(b))
  expect_equal(logb(2/5, base = 5), logb(b, base = 5))
  expect_equal(log2(2/5), log2(b))
  expect_equal(gamma(2/5), gamma(b))
  expect_true(3 == max(rational(c(2L, 3L), c(5L, 1L), "S3")))
  expect_true(2/5 == min(rational(c(2L, 3L), c(5L, 1L), "S3")))
  expect_true(is.list(range(rational(c(2L, 3L), c(5L, 1L), "S3"))))
  expect_true(range(rational(c(2L, 3L), c(5L, 1L), "S3"))[[1]] == rational(2L, 5L, "S3"))
  expect_true(6/5 == prod(rational(c(2L, 3L), c(5L, 1L), "S3")))
  expect_true(17/5 == sum(rational(c(2L, 3L), c(5L, 1L), "S3")))
})

testthat::test_that("Test R6 functions", {
  a <- rational(5L, 2L, "R6")
  expect_equal(2, floor(a))
  expect_equal(-1, sign(rational(-1L, 2L, "R6")))
  expect_equal(2, round(rational(5L, 2L, "R6"), 0))
  x <- abs(rational(-2L, 3L, "R6"))
  expect_true("rationalR6" %in% class(x))
  expect_true(2/3 == abs(x))
  b <- rational(2L, 5L, "R6")
  expect_equal(log(2/5), log(b))
  expect_equal(log10(2/5), log10(b))
  expect_equal(logb(2/5, base = 5), logb(b, base = 5))
  expect_equal(log2(2/5), log2(b))
  expect_equal(gamma(2/5), gamma(b))
  expect_true(3 == max(rational(c(2L, 3L), c(5L, 1L), "R6")))
  expect_true(2/5 == min(rational(c(2L, 3L), c(5L, 1L), "R6")))
  expect_true(is.list(range(rational(c(2L, 3L), c(5L, 1L), "R6"))))
  expect_true(range(rational(c(2L, 3L), c(5L, 1L), "R6"))[[1]] == rational(2L, 5L, "R6"))
  expect_true(6/5 == prod(rational(c(2L, 3L), c(5L, 1L), "R6")))
  expect_true(17/5 == sum(rational(c(2L, 3L), c(5L, 1L), "R6")))
})
